"""detectors ai conclusion

Revision ID: 4c68e9dce23c
Revises: a4d9c7e21b58
Create Date: 2026-09-02 01:36:53.855884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c68e9dce23c'
down_revision: Union[str, Sequence[str], None] = 'a4d9c7e21b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detectors_conclusion',
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('well_id', sa.BigInteger(), nullable=False),
    sa.Column('detector_code', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['detectors_incident.id'], name=op.f('fk_detectors_conclusion_incident_id_detectors_incident')),
    sa.ForeignKeyConstraint(['well_id'], ['wells_well.id'], name=op.f('fk_detectors_conclusion_well_id_wells_well')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detectors_conclusion')),
    sa.UniqueConstraint('incident_id', 'level', name='uq_detectors_conclusion_incident_level')
    )
    op.create_index(op.f('ix_detectors_conclusion_id'), 'detectors_conclusion', ['id'], unique=False)
    op.create_table('detectors_conclusion_feedback',
    sa.Column('conclusion_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conclusion_id'], ['detectors_conclusion.id'], name=op.f('fk_detectors_conclusion_feedback_conclusion_id_detectors_conclusion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detectors_conclusion_feedback'))
    )
    op.create_index(op.f('ix_detectors_conclusion_feedback_id'), 'detectors_conclusion_feedback', ['id'], unique=False)
    op.create_index('ix_detectors_conclusion_well_id', 'detectors_conclusion', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detectors_conclusion_well_id', table_name='detectors_conclusion')
    op.drop_index(op.f('ix_detectors_conclusion_feedback_id'), table_name='detectors_conclusion_feedback')
    op.drop_table('detectors_conclusion_feedback')
    op.drop_index(op.f('ix_detectors_conclusion_id'), table_name='detectors_conclusion')
    op.drop_table('detectors_conclusion')
    # ### end Alembic commands ###
