"""add sdmo telemetry tables

Revision ID: da32830be32d
Revises: 4d7ee131259b
Create Date: 2026-07-20 21:45:56.356037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da32830be32d'
down_revision: Union[str, Sequence[str], None] = '4d7ee131259b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_sdmo_fc_data',
    sa.Column('sdmo_id', sa.BigInteger(), nullable=False),
    sa.Column('sdmo_station_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('savetime', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_sdmo_fc_data')),
    sa.UniqueConstraint('sdmo_station_id', 'day', name='uq_telemetry_sdmo_fc_data_station_day')
    )
    op.create_index(op.f('ix_telemetry_sdmo_fc_data_day'), 'telemetry_sdmo_fc_data', ['day'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_fc_data_id'), 'telemetry_sdmo_fc_data', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_fc_data_sdmo_id'), 'telemetry_sdmo_fc_data', ['sdmo_id'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_fc_data_sdmo_station_id'), 'telemetry_sdmo_fc_data', ['sdmo_station_id'], unique=False)
    op.create_table('telemetry_sdmo_fc_reg',
    sa.Column('sdmo_id', sa.BigInteger(), nullable=False),
    sa.Column('type_1900', sa.Integer(), nullable=True),
    sa.Column('addr', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('units', sa.String(length=45), nullable=True),
    sa.Column('koef', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('dynamic', sa.Boolean(), nullable=True),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('lora_bytes_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_sdmo_fc_reg')),
    sa.UniqueConstraint('type_1900', 'addr', name='uq_telemetry_sdmo_fc_reg_type_1900_addr')
    )
    op.create_index(op.f('ix_telemetry_sdmo_fc_reg_addr'), 'telemetry_sdmo_fc_reg', ['addr'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_fc_reg_id'), 'telemetry_sdmo_fc_reg', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_fc_reg_sdmo_id'), 'telemetry_sdmo_fc_reg', ['sdmo_id'], unique=True)
    op.create_table('telemetry_sdmo_station',
    sa.Column('sdmo_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('type_1900', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('well_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells_well.id'], name=op.f('fk_telemetry_sdmo_station_well_id_wells_well')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_sdmo_station'))
    )
    op.create_index(op.f('ix_telemetry_sdmo_station_code'), 'telemetry_sdmo_station', ['code'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_station_id'), 'telemetry_sdmo_station', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_sdmo_station_sdmo_id'), 'telemetry_sdmo_station', ['sdmo_id'], unique=True)
    op.create_index(op.f('ix_telemetry_sdmo_station_well_id'), 'telemetry_sdmo_station', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_sdmo_station_well_id'), table_name='telemetry_sdmo_station')
    op.drop_index(op.f('ix_telemetry_sdmo_station_sdmo_id'), table_name='telemetry_sdmo_station')
    op.drop_index(op.f('ix_telemetry_sdmo_station_id'), table_name='telemetry_sdmo_station')
    op.drop_index(op.f('ix_telemetry_sdmo_station_code'), table_name='telemetry_sdmo_station')
    op.drop_table('telemetry_sdmo_station')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_reg_sdmo_id'), table_name='telemetry_sdmo_fc_reg')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_reg_id'), table_name='telemetry_sdmo_fc_reg')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_reg_addr'), table_name='telemetry_sdmo_fc_reg')
    op.drop_table('telemetry_sdmo_fc_reg')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_data_sdmo_station_id'), table_name='telemetry_sdmo_fc_data')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_data_sdmo_id'), table_name='telemetry_sdmo_fc_data')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_data_id'), table_name='telemetry_sdmo_fc_data')
    op.drop_index(op.f('ix_telemetry_sdmo_fc_data_day'), table_name='telemetry_sdmo_fc_data')
    op.drop_table('telemetry_sdmo_fc_data')
    # ### end Alembic commands ###
