"""empty message

Revision ID: dc7ea8404645
Revises:
Create Date: 2026-07-07 17:55:52.731319

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc7ea8404645"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table(
        "files_file",
        sa.Column("file", sa.String(length=500), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files_file")),
    )
    op.create_index(op.f("ix_files_file_id"), "files_file", ["id"], unique=False)
    op.create_table(
        "org",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name_ru", sa.String(), nullable=False),
        sa.Column("name_ru_short", sa.String(), nullable=True),
        sa.Column("org_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_org_abai_id")),
    )
    op.create_index(op.f("ix_org_id"), "org", ["id"], unique=False)
    op.create_table(
        "org_brigade",
        sa.Column("name_ru", sa.String(), nullable=False),
        sa.Column("name_ru_short", sa.String(), nullable=True),
        sa.Column("own", sa.Boolean(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_brigade")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_org_brigade_abai_id")),
    )
    op.create_index(op.f("ix_org_brigade_id"), "org_brigade", ["id"], unique=False)
    op.create_table(
        "org_ngdu",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_ngdu")),
    )
    op.create_index(op.f("ix_org_ngdu_id"), "org_ngdu", ["id"], unique=False)
    op.create_table(
        "org_type",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_type")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_org_type_abai_id")),
    )
    op.create_index(op.f("ix_org_type_id"), "org_type", ["id"], unique=False)
    op.create_table(
        "repairs_repair_type",
        sa.Column("name_ru", sa.Text(), nullable=False),
        sa.Column("name_ru_short", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_type")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_repairs_repair_type_abai_id")),
    )

    op.create_index(
        op.f("ix_repairs_repair_type_id"),
        "repairs_repair_type",
        ["id"],
        unique=False,
    )
    op.create_table(
        "wells_coord_system",
        sa.Column("mn", sa.Text(), nullable=False),
        sa.Column("name_ru", sa.Text(), nullable=False),
        sa.Column("srid", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells_coord_system")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_wells_coord_system_abai_id")),
    )
    op.create_index(
        op.f("ix_wells_coord_system_id"),
        "wells_coord_system",
        ["id"],
        unique=False,
    )
    op.create_table(
        "wells_coord",
        sa.Column("coords_system_id", sa.BigInteger(), nullable=True),
        sa.Column("spatial_object_type", sa.Integer(), nullable=False),
        sa.Column(
            "coord_point",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "coord_polygon",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coords_system_id"],
            ["wells_coord_system.abai_id"],
            name=op.f("fk_wells_coord_coords_system_id_wells_coord_system"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells_coord")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_wells_coord_abai_id")),
    )
    op.create_index(op.f("ix_wells_coord_id"), "wells_coord", ["id"], unique=False)
    op.create_table(
        "wells_well",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.Column("coords_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coords_id"],
            ["wells_coord.abai_id"],
            name=op.f("fk_wells_well_coords_id_wells_coord"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells_well")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_wells_well_abai_id")),
        sa.UniqueConstraint("name", name=op.f("uq_wells_well_name")),
    )
    op.create_table(
        "repairs_dynamogram",
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_time", sa.DateTime(), nullable=False),
        sa.Column("well_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files_file.id"],
            name=op.f("fk_repairs_dynamogram_file_id_files_file"),
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells_well.id"],
            name=op.f("fk_repairs_dynamogram_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_dynamogram")),
    )
    op.create_index(
        op.f("ix_repairs_dynamogram_id"),
        "repairs_dynamogram",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair",
        sa.Column("well_id", sa.BigInteger(), nullable=True),
        sa.Column("abai_well_id", sa.BigInteger(), nullable=False),
        sa.Column("work_list", sa.Text(), nullable=True),
        sa.Column("work_plan", sa.Text(), nullable=True),
        sa.Column("repair_type_id", sa.BigInteger(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["abai_well_id"],
            ["wells_well.abai_id"],
            name=op.f("fk_repairs_repair_abai_well_id_wells_well"),
        ),
        sa.ForeignKeyConstraint(
            ["repair_type_id"],
            ["repairs_repair_type.abai_id"],
            name=op.f("fk_repairs_repair_repair_type_id_repairs_repair_type"),
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells_well.id"],
            name=op.f("fk_repairs_repair_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_repairs_repair_abai_id")),
    )
    op.create_index(
        op.f("ix_repairs_repair_end_time"),
        "repairs_repair",
        ["end_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repairs_repair_id"),
        "repairs_repair",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repairs_repair_start_time"),
        "repairs_repair",
        ["start_time"],
        unique=False,
    )
    op.create_table(
        "repairs_spo",
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("chart_file_id", sa.BigInteger(), nullable=True),
        sa.Column("notes_file_id", sa.BigInteger(), nullable=True),
        sa.Column("snapshot_time", sa.DateTime(), nullable=False),
        sa.Column("well_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["chart_file_id"],
            ["files_file.id"],
            name=op.f("fk_repairs_spo_chart_file_id_files_file"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files_file.id"],
            name=op.f("fk_repairs_spo_file_id_files_file"),
        ),
        sa.ForeignKeyConstraint(
            ["notes_file_id"],
            ["files_file.id"],
            name=op.f("fk_repairs_spo_notes_file_id_files_file"),
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells_well.id"],
            name=op.f("fk_repairs_spo_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_spo")),
    )
    op.create_index(op.f("ix_repairs_spo_id"), "repairs_spo", ["id"], unique=False)
    op.create_table(
        "telemetry_tech_regime",
        sa.Column("abai_well_id", sa.BigInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("liquid", sa.Float(), nullable=True),
        sa.Column("oil", sa.Float(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["abai_well_id"],
            ["wells_well.abai_id"],
            name=op.f("fk_telemetry_tech_regime_abai_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_tech_regime")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_telemetry_tech_regime_abai_id")),
    )
    op.create_index(
        op.f("ix_telemetry_tech_regime_id"),
        "telemetry_tech_regime",
        ["id"],
        unique=False,
    )
    op.create_table(
        "telemetry_well",
        sa.Column("well_id", sa.BigInteger(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column("qv_liquid", sa.Float(), nullable=True),
        sa.Column("qm_oil", sa.Float(), nullable=True),
        sa.Column("ngdu_id", sa.BigInteger(), nullable=False),
        sa.Column("oil_field", sa.String(length=10), nullable=True),
        sa.Column("gzu", sa.String(length=10), nullable=True),
        sa.Column("otvod", sa.String(length=10), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["ngdu_id"],
            ["org_ngdu.id"],
            name=op.f("fk_telemetry_well_ngdu_id_org_ngdu"),
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells_well.id"],
            name=op.f("fk_telemetry_well_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_well")),
    )
    op.create_index(
        op.f("ix_telemetry_well_id"),
        "telemetry_well",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_dynamogram_ai_result",
        sa.Column("dynamogram_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dynamogram_id"],
            ["repairs_dynamogram.id"],
            name=op.f(
                "fk_repairs_dynamogram_ai_result_dynamogram_id_repairs_dynamogram",
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_dynamogram_ai_result")),
        sa.UniqueConstraint(
            "dynamogram_id",
            name=op.f("uq_repairs_dynamogram_ai_result_dynamogram_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_dynamogram_ai_result_id"),
        "repairs_dynamogram_ai_result",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_docs",
        sa.Column("repair_id", sa.BigInteger(), nullable=True),
        sa.Column("act_file_id", sa.BigInteger(), nullable=True),
        sa.Column("por_file_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["act_file_id"],
            ["files_file.id"],
            name=op.f("fk_repairs_repair_docs_act_file_id_files_file"),
        ),
        sa.ForeignKeyConstraint(
            ["por_file_id"],
            ["files_file.id"],
            name=op.f("fk_repairs_repair_docs_por_file_id_files_file"),
        ),
        sa.ForeignKeyConstraint(
            ["repair_id"],
            ["repairs_repair.id"],
            name=op.f("fk_repairs_repair_docs_repair_id_repairs_repair"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_docs")),
        sa.UniqueConstraint("repair_id", name=op.f("uq_repairs_repair_docs_repair_id")),
    )
    op.create_index(
        op.f("ix_repairs_repair_docs_id"),
        "repairs_repair_docs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_reports",
        sa.Column("repair_id", sa.BigInteger(), nullable=True),
        sa.Column("well_id", sa.BigInteger(), nullable=False),
        sa.Column("second_well_id", sa.BigInteger(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("brigade_number", sa.Integer(), nullable=False),
        sa.Column("pump_type", sa.String(length=255), nullable=False),
        sa.Column("shift_type_number", sa.Integer(), nullable=False),
        sa.Column("car", sa.String(length=255), nullable=False),
        sa.Column("device_number", sa.String(length=255), nullable=False),
        sa.Column("shift_details", sa.JSON(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["repair_id"],
            ["repairs_repair.id"],
            name=op.f("fk_repairs_repair_reports_repair_id_repairs_repair"),
        ),
        sa.ForeignKeyConstraint(
            ["second_well_id"],
            ["wells_well.id"],
            name=op.f("fk_repairs_repair_reports_second_well_id_wells_well"),
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells_well.id"],
            name=op.f("fk_repairs_repair_reports_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_reports")),
        sa.UniqueConstraint(
            "well_id",
            "date",
            name="uq_repairs_repair_reports_well_id_date",
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_reports_id"),
        "repairs_repair_reports",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_spo_ai_result",
        sa.Column("spo_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["spo_id"],
            ["repairs_spo.id"],
            name=op.f("fk_repairs_spo_ai_result_spo_id_repairs_spo"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_spo_ai_result")),
        sa.UniqueConstraint("spo_id", name=op.f("uq_repairs_spo_ai_result_spo_id")),
    )
    op.create_index(
        op.f("ix_repairs_spo_ai_result_id"),
        "repairs_spo_ai_result",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_analytics",
        sa.Column("repair_id", sa.BigInteger(), nullable=False),
        sa.Column("summary_id", sa.BigInteger(), nullable=True),
        sa.Column("repair_docs_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "is_finalized",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repair_docs_id"],
            ["repairs_repair_docs.id"],
            name=op.f("fk_repairs_repair_analytics_repair_docs_id_repairs_repair_docs"),
        ),
        sa.ForeignKeyConstraint(
            ["repair_id"],
            ["repairs_repair.id"],
            name=op.f("fk_repairs_repair_analytics_repair_id_repairs_repair"),
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["repairs_repair_reports.id"],
            name=op.f("fk_repairs_repair_analytics_summary_id_repairs_repair_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_analytics")),
        sa.UniqueConstraint(
            "repair_id",
            name=op.f("uq_repairs_repair_analytics_repair_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_analytics_id"),
        "repairs_repair_analytics",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_ai_analysis",
        sa.Column("analytics_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analytics_id"],
            ["repairs_repair_analytics.id"],
            name=op.f(
                "fk_repairs_repair_ai_analysis_analytics_id_repairs_repair_analytics",
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_ai_analysis")),
        sa.UniqueConstraint(
            "analytics_id",
            name=op.f("uq_repairs_repair_ai_analysis_analytics_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_ai_analysis_id"),
        "repairs_repair_ai_analysis",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_analytics_brigade_error_screen",
        sa.Column("analytics_id", sa.BigInteger(), nullable=False),
        sa.Column("cm_screen_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analytics_id"],
            ["repairs_repair_analytics.id"],
            name=op.f(
                "fk_repairs_repair_analytics_brigade_error_screen_analytics_id_repairs_repair_analytics",
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_repairs_repair_analytics_brigade_error_screen"),
        ),
        sa.UniqueConstraint(
            "analytics_id",
            name=op.f("uq_repairs_repair_analytics_brigade_error_screen_analytics_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_analytics_brigade_error_screen_id"),
        "repairs_repair_analytics_brigade_error_screen",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_analytics_dynamogram",
        sa.Column("analytics_id", sa.BigInteger(), nullable=False),
        sa.Column("dynamogram_before_id", sa.BigInteger(), nullable=True),
        sa.Column("dynamogram_after_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analytics_id"],
            ["repairs_repair_analytics.id"],
            name=op.f(
                "fk_repairs_repair_analytics_dynamogram_analytics_id_repairs_repair_analytics",
            ),
        ),
        sa.ForeignKeyConstraint(
            ["dynamogram_after_id"],
            ["repairs_dynamogram.id"],
            name=op.f(
                "fk_repairs_repair_analytics_dynamogram_dynamogram_after_id_repairs_dynamogram",
            ),
        ),
        sa.ForeignKeyConstraint(
            ["dynamogram_before_id"],
            ["repairs_dynamogram.id"],
            name=op.f(
                "fk_repairs_repair_analytics_dynamogram_dynamogram_before_id_repairs_dynamogram",
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_repairs_repair_analytics_dynamogram"),
        ),
        sa.UniqueConstraint(
            "analytics_id",
            name=op.f("uq_repairs_repair_analytics_dynamogram_analytics_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_analytics_dynamogram_id"),
        "repairs_repair_analytics_dynamogram",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_analytics_spo",
        sa.Column("analytics_id", sa.BigInteger(), nullable=False),
        sa.Column("spo_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analytics_id"],
            ["repairs_repair_analytics.id"],
            name=op.f(
                "fk_repairs_repair_analytics_spo_analytics_id_repairs_repair_analytics",
            ),
        ),
        sa.ForeignKeyConstraint(
            ["spo_id"],
            ["repairs_spo.id"],
            name=op.f("fk_repairs_repair_analytics_spo_spo_id_repairs_spo"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_analytics_spo")),
        sa.UniqueConstraint(
            "analytics_id",
            name=op.f("uq_repairs_repair_analytics_spo_analytics_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_analytics_spo_id"),
        "repairs_repair_analytics_spo",
        ["id"],
        unique=False,
    )
    op.create_index(
        "idx_wells_coord_coord_point",
        "wells_coord",
        ["coord_point"],
        unique=False,
        postgresql_using="gist",
    )

    op.create_index(
        "idx_wells_coord_coord_polygon",
        "wells_coord",
        ["coord_polygon"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_repairs_repair_analytics_spo_id"),
        table_name="repairs_repair_analytics_spo",
    )
    op.drop_table("repairs_repair_analytics_spo")
    op.drop_index(
        op.f("ix_repairs_repair_analytics_dynamogram_id"),
        table_name="repairs_repair_analytics_dynamogram",
    )
    op.drop_table("repairs_repair_analytics_dynamogram")
    op.drop_index(
        op.f("ix_repairs_repair_analytics_brigade_error_screen_id"),
        table_name="repairs_repair_analytics_brigade_error_screen",
    )
    op.drop_table("repairs_repair_analytics_brigade_error_screen")
    op.drop_index(
        op.f("ix_repairs_repair_ai_analysis_id"),
        table_name="repairs_repair_ai_analysis",
    )
    op.drop_table("repairs_repair_ai_analysis")
    op.drop_index(
        op.f("ix_repairs_repair_analytics_id"),
        table_name="repairs_repair_analytics",
    )
    op.drop_table("repairs_repair_analytics")
    op.drop_index(
        op.f("ix_repairs_spo_ai_result_id"),
        table_name="repairs_spo_ai_result",
    )
    op.drop_table("repairs_spo_ai_result")
    op.drop_index(
        op.f("ix_repairs_repair_reports_id"),
        table_name="repairs_repair_reports",
    )
    op.drop_table("repairs_repair_reports")
    op.drop_index(op.f("ix_repairs_repair_docs_id"), table_name="repairs_repair_docs")
    op.drop_table("repairs_repair_docs")
    op.drop_index(
        op.f("ix_repairs_dynamogram_ai_result_id"),
        table_name="repairs_dynamogram_ai_result",
    )
    op.drop_table("repairs_dynamogram_ai_result")
    op.drop_index(op.f("ix_telemetry_well_id"), table_name="telemetry_well")
    op.drop_table("telemetry_well")
    op.drop_index(
        op.f("ix_telemetry_tech_regime_id"),
        table_name="telemetry_tech_regime",
    )
    op.drop_table("telemetry_tech_regime")
    op.drop_index(op.f("ix_repairs_spo_id"), table_name="repairs_spo")
    op.drop_table("repairs_spo")
    op.drop_index(op.f("ix_repairs_repair_start_time"), table_name="repairs_repair")
    op.drop_index(op.f("ix_repairs_repair_id"), table_name="repairs_repair")
    op.drop_index(op.f("ix_repairs_repair_end_time"), table_name="repairs_repair")
    op.drop_table("repairs_repair")
    op.drop_index(op.f("ix_repairs_dynamogram_id"), table_name="repairs_dynamogram")
    op.drop_table("repairs_dynamogram")
    op.drop_table("wells_well")
    op.drop_index(op.f("ix_wells_coord_id"), table_name="wells_coord")
    op.drop_table("wells_coord")
    op.drop_index(op.f("ix_wells_coord_system_id"), table_name="wells_coord_system")
    op.drop_table("wells_coord_system")
    op.drop_index(op.f("ix_repairs_repair_type_id"), table_name="repairs_repair_type")
    op.drop_table("repairs_repair_type")
    op.drop_index(op.f("ix_org_type_id"), table_name="org_type")
    op.drop_table("org_type")
    op.drop_index(op.f("ix_org_ngdu_id"), table_name="org_ngdu")
    op.drop_table("org_ngdu")
    op.drop_index(op.f("ix_org_brigade_id"), table_name="org_brigade")
    op.drop_table("org_brigade")
    op.drop_index(op.f("ix_org_id"), table_name="org")
    op.drop_table("org")
    op.drop_index(op.f("ix_files_file_id"), table_name="files_file")
    op.drop_table("files_file")
    # ### end Alembic commands ###
