"""add wells gdis tables

Зеркало ГДИС из ABAI: справочник метрик (wells_gdis_metric), исследования
скважин (wells_gdis_current) и значения метрик (wells_gdis_current_value).
Связи по ABAI id, как у остальных зеркал.

Revision ID: cd447c125022
Revises: 62425057e44f
Create Date: 2026-09-08 16:23:23.282782

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cd447c125022"
down_revision: str | Sequence[str] | None = "62425057e44f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wells_gdis_metric",
        sa.Column("name_ru", sa.Text(), nullable=False),
        sa.Column("name_short_ru", sa.Text(), nullable=True),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("data_type", sa.BigInteger(), nullable=True),
        sa.Column("parent_abai_id", sa.BigInteger(), nullable=True),
        sa.Column("dict_table", sa.Text(), nullable=True),
        sa.Column("value_double_min", sa.Float(), nullable=True),
        sa.Column("value_double_max", sa.Float(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells_gdis_metric")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_wells_gdis_metric_abai_id")),
    )
    op.create_index(
        op.f("ix_wells_gdis_metric_code"),
        "wells_gdis_metric",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wells_gdis_metric_id"),
        "wells_gdis_metric",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wells_gdis_metric_parent_abai_id"),
        "wells_gdis_metric",
        ["parent_abai_id"],
        unique=False,
    )
    op.create_table(
        "wells_gdis_current",
        sa.Column("abai_well_id", sa.BigInteger(), nullable=False),
        sa.Column("meas_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.BigInteger(), nullable=True),
        sa.Column("reason_txt", sa.Text(), nullable=True),
        sa.Column("device", sa.BigInteger(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("transcript_dynamogram", sa.Text(), nullable=True),
        sa.Column("conclusion", sa.BigInteger(), nullable=True),
        sa.Column("conclusion_arr", postgresql.ARRAY(sa.BigInteger()), nullable=True),
        sa.Column("conclusion_text", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["abai_well_id"],
            ["wells_well.abai_id"],
            name=op.f("fk_wells_gdis_current_abai_well_id_wells_well"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells_gdis_current")),
        sa.UniqueConstraint("abai_id", name=op.f("uq_wells_gdis_current_abai_id")),
    )
    op.create_index(
        "ix_wells_gdis_current_abai_well_id_meas_date",
        "wells_gdis_current",
        ["abai_well_id", "meas_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wells_gdis_current_id"),
        "wells_gdis_current",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wells_gdis_current_meas_date"),
        "wells_gdis_current",
        ["meas_date"],
        unique=False,
    )
    op.create_table(
        "wells_gdis_current_value",
        sa.Column("gdis_current_abai_id", sa.BigInteger(), nullable=False),
        sa.Column("metric_abai_id", sa.BigInteger(), nullable=False),
        sa.Column("value_double", sa.Float(), nullable=True),
        sa.Column("value_string", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("abai_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdis_current_abai_id"],
            ["wells_gdis_current.abai_id"],
            name=op.f(
                "fk_wells_gdis_current_value_gdis_current_abai_id_wells_gdis_current",
            ),
        ),
        sa.ForeignKeyConstraint(
            ["metric_abai_id"],
            ["wells_gdis_metric.abai_id"],
            name=op.f("fk_wells_gdis_current_value_metric_abai_id_wells_gdis_metric"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wells_gdis_current_value")),
        sa.UniqueConstraint(
            "abai_id",
            name=op.f("uq_wells_gdis_current_value_abai_id"),
        ),
    )
    op.create_index(
        "ix_wells_gdis_current_value_gdis_metric",
        "wells_gdis_current_value",
        ["gdis_current_abai_id", "metric_abai_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wells_gdis_current_value_id"),
        "wells_gdis_current_value",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wells_gdis_current_value_metric_abai_id"),
        "wells_gdis_current_value",
        ["metric_abai_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wells_gdis_current_value_metric_abai_id"),
        table_name="wells_gdis_current_value",
    )
    op.drop_index(
        op.f("ix_wells_gdis_current_value_id"),
        table_name="wells_gdis_current_value",
    )
    op.drop_index(
        "ix_wells_gdis_current_value_gdis_metric",
        table_name="wells_gdis_current_value",
    )
    op.drop_table("wells_gdis_current_value")
    op.drop_index(
        op.f("ix_wells_gdis_current_meas_date"),
        table_name="wells_gdis_current",
    )
    op.drop_index(op.f("ix_wells_gdis_current_id"), table_name="wells_gdis_current")
    op.drop_index(
        "ix_wells_gdis_current_abai_well_id_meas_date",
        table_name="wells_gdis_current",
    )
    op.drop_table("wells_gdis_current")
    op.drop_index(
        op.f("ix_wells_gdis_metric_parent_abai_id"),
        table_name="wells_gdis_metric",
    )
    op.drop_index(op.f("ix_wells_gdis_metric_id"), table_name="wells_gdis_metric")
    op.drop_index(op.f("ix_wells_gdis_metric_code"), table_name="wells_gdis_metric")
    op.drop_table("wells_gdis_metric")
    # ### end Alembic commands ###
