"""empty message

Revision ID: 6a516cd8a26a
Revises: 9a045558c77e
Create Date: 2026-07-07 21:32:43.190211

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a516cd8a26a"
down_revision: str | Sequence[str] | None = "9a045558c77e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repairs_spo_event",
        sa.Column("spo_id", sa.BigInteger(), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=False),
        sa.Column("time_text", sa.String(length=64), nullable=True),
        sa.Column("code", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["spo_id"],
            ["repairs_spo.id"],
            name=op.f("fk_repairs_spo_event_spo_id_repairs_spo"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_spo_event")),
    )
    op.create_index(
        op.f("ix_repairs_spo_event_id"),
        "repairs_spo_event",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repairs_spo_event_spo_id"),
        "repairs_spo_event",
        ["spo_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repairs_spo_event_spo_id"), table_name="repairs_spo_event")
    op.drop_index(op.f("ix_repairs_spo_event_id"), table_name="repairs_spo_event")
    op.drop_table("repairs_spo_event")
    # ### end Alembic commands ###
