"""empty message

Revision ID: 9a045558c77e
Revises: dc7ea8404645
Create Date: 2026-07-07 18:21:24.878662

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a045558c77e"
down_revision: str | Sequence[str] | None = "dc7ea8404645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telemetry_well",
        sa.Column("abai_ngdu_id", sa.BigInteger(), nullable=False),
    )
    op.create_index(
        op.f("ix_telemetry_well_abai_ngdu_id"),
        "telemetry_well",
        ["abai_ngdu_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_telemetry_well_ngdu_id_org_ngdu"),
        "telemetry_well",
        type_="foreignkey",
    )
    op.drop_column("telemetry_well", "ngdu_id")
    op.drop_index(
        op.f("idx_wells_coord_coord_point"),
        table_name="wells_coord",
        postgresql_using="gist",
    )
    op.drop_index(
        op.f("idx_wells_coord_coord_polygon"),
        table_name="wells_coord",
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_wells_coord_coord_polygon"),
        "wells_coord",
        ["coord_polygon"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("idx_wells_coord_coord_point"),
        "wells_coord",
        ["coord_point"],
        unique=False,
        postgresql_using="gist",
    )
    op.add_column(
        "telemetry_well",
        sa.Column("ngdu_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_telemetry_well_ngdu_id_org_ngdu"),
        "telemetry_well",
        "org_ngdu",
        ["ngdu_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_telemetry_well_abai_ngdu_id"), table_name="telemetry_well")
    op.drop_column("telemetry_well", "abai_ngdu_id")
    # ### end Alembic commands ###
