"""empty message

Revision ID: eade073c8d53
Revises: 6a516cd8a26a
Create Date: 2026-07-08 00:19:20.232243

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eade073c8d53"
down_revision: str | Sequence[str] | None = "6a516cd8a26a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_unique_brigade",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ngdu_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["ngdu_id"],
            ["org.id"],
            name=op.f("fk_org_unique_brigade_ngdu_id_org"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_unique_brigade")),
        sa.UniqueConstraint("name", "ngdu_id", name="uq_org_unique_brigade_name_ngdu"),
    )
    op.create_index(
        op.f("ix_org_unique_brigade_id"),
        "org_unique_brigade",
        ["id"],
        unique=False,
    )
    op.create_table(
        "repairs_repair_brigade",
        sa.Column("repair_id", sa.BigInteger(), nullable=False),
        sa.Column("brigade_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["brigade_id"],
            ["org_unique_brigade.id"],
            name=op.f("fk_repairs_repair_brigade_brigade_id_org_unique_brigade"),
        ),
        sa.ForeignKeyConstraint(
            ["repair_id"],
            ["repairs_repair.id"],
            name=op.f("fk_repairs_repair_brigade_repair_id_repairs_repair"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_brigade")),
    )
    op.create_index(
        op.f("ix_repairs_repair_brigade_id"),
        "repairs_repair_brigade",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_repairs_repair_brigade_id"),
        table_name="repairs_repair_brigade",
    )
    op.drop_table("repairs_repair_brigade")
    op.drop_index(op.f("ix_org_unique_brigade_id"), table_name="org_unique_brigade")
    op.drop_table("org_unique_brigade")
    # ### end Alembic commands ###
