"""empty message

Revision ID: 4d7ee131259b
Revises: 507de88a102e
Create Date: 2026-07-16 12:18:30.030905

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d7ee131259b"
down_revision: str | Sequence[str] | None = "507de88a102e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repairs_spo",
        sa.Column("chart_json_file_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "repairs_spo",
        sa.Column("passport_file_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_repairs_spo_passport_file_id_files_file"),
        "repairs_spo",
        "files_file",
        ["passport_file_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_repairs_spo_chart_json_file_id_files_file"),
        "repairs_spo",
        "files_file",
        ["chart_json_file_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_repairs_spo_chart_json_file_id_files_file"),
        "repairs_spo",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_repairs_spo_passport_file_id_files_file"),
        "repairs_spo",
        type_="foreignkey",
    )
    op.drop_column("repairs_spo", "passport_file_id")
    op.drop_column("repairs_spo", "chart_json_file_id")
    # ### end Alembic commands ###
