"""empty message

Revision ID: 0df117be908a
Revises: eade073c8d53
Create Date: 2026-07-08 00:51:53.049653

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0df117be908a"
down_revision: str | Sequence[str] | None = "eade073c8d53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_repairs_repair_brigade_repair_id"),
        "repairs_repair_brigade",
        ["repair_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_repairs_repair_brigade_repair_id"),
        "repairs_repair_brigade",
        type_="unique",
    )

    # ### end Alembic commands ###
