"""add repairs_repair_kpi

Revision ID: a1b2c3d4e5f6
Revises: 0df117be908a
Create Date: 2026-07-13 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "0df117be908a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repairs_repair_kpi",
        sa.Column("analytics_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analytics_id"],
            ["repairs_repair_analytics.id"],
            name=op.f("fk_repairs_repair_kpi_analytics_id_repairs_repair_analytics"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repairs_repair_kpi")),
        sa.UniqueConstraint(
            "analytics_id",
            name=op.f("uq_repairs_repair_kpi_analytics_id"),
        ),
    )
    op.create_index(
        op.f("ix_repairs_repair_kpi_id"),
        "repairs_repair_kpi",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_repairs_repair_kpi_id"),
        table_name="repairs_repair_kpi",
    )
    op.drop_table("repairs_repair_kpi")
    # ### end Alembic commands ###
