from io import BytesIO
from typing import Protocol


class AiobotoClient(Protocol):
    async def upload_fileobj(self, Fileobj: BytesIO, Bucket: str, Key: str) -> None: ...
    async def upload_file(self, Filename: str, Bucket: str, Key: str) -> None: ...
    async def download_fileobj(
        self,
        Bucket: str,
        Key: str,
        Fileobj: BytesIO,
    ) -> None: ...
    async def download_file(self, Bucket: str, Key: str, Filename: str) -> None: ...
    async def delete_object(self, Bucket: str, Key: str) -> None: ...
    async def head_object(self, Bucket: str, Key: str) -> dict: ...
    async def list_objects_v2(self, Bucket: str, Prefix: str) -> dict: ...
    async def generate_presigned_url(
        self,
        ClientMethod: str,
        Params: dict,
        ExpiresIn: int,
    ) -> str: ...
